# Generated by Django 3.2.23 on 2024-01-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_has_tag', '0001_initial'),
        ('tag', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', through='product_has_tag.ProductHasTag', to='tag.Tag'),
        ),
    ]
